ViewModels/AdvertisePropertyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SS.ViewModels
{
    public class AdvertisePropertyViewModel
    {
        public String Title { get; set; }
        public String PropertyCategory { get; set; }
        public String PropertyPurpose { get; set; }
        public String PropertyType { get; set; }
        public String AdvertismentType { get; set; }
        public String AdvertismentPriority { get; set; }
        public String SubscriptionType { get; set; }
        public int SubscriptionPeriod { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String CellNum { get; set; }
        public String AreaCode { get; set; }
        public String Email { get; set; }
        public String Organization { get; set; }
        public String Password { get; set; }
        public String ConfirmPassword { get; set; }
        public String StreetAddress { get; set; }
        public String Country { get; set; }
        public String Division { get; set; }
        public String Community { get; set; }
        public String NearBy { get; set; }
        public decimal Price { get; set; }
        public decimal SecurityDeposit { get; set; }
        public int Occupancy { get; set; }
        public String GenderPreferenceCode { get; set; }
        public int TotAvailableBathroom { get; set; }
        public int TotRooms { get; set; }
        public decimal Area { get; set; }
        public bool IsReviewable { get; set; }
        public String Description { get; set; }
        public String EnrolmentKey { get; set; }
        public String TermsAgreement { get; set; }
        public String[] selectedTags { get; set; }
        //street address location
        public String saCoordinateLat { get; set; }
        public String saCoordinateLng { get; set; }
        //community location
        public String cCoordinateLat { get; set; }
        public String cCoordinateLng { get; set; }
        //establishment near by location
        public String nearByCoordinateLat { get; set; }
        public String nearByCoordinateLng { get; set; }
        public HttpPostedFileBase organizationLogo { get; set; }
        public HttpPostedFileBase[] flPropertyPics { get; set; }
        public List<Models.SubscriptionType> SubscriptionTypes;
    }
}

ViewModels/RequisitionViewModel.cs
using SS.Models;
using System;

namespace SS.ViewModels
{
    public class RequisitionViewModel
    {
        public String ImageUrl { get; set; }
        public PropertyRequisition PropertyRequisition;
        public bool isUserPropOwner { get; set; }

        public RequisitionViewModel()
        {
            this.PropertyRequisition = new PropertyRequisition();
        }
    }
}

Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SS.Models;
using System.IO;
using System.Web.Security;
using SS.Code;
using System.Globalization;
using System.Text;
using SS.Core;
using SS.ViewModels;
using log4net;
using SS.Services;

namespace SS.Controllers
{
    public class AccountsController : Controller
    {
        private static readonly ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private readonly PropertyService propertyService;
        private readonly UserService userService;
        private readonly SubscriptionService subscriptionService;

        public AccountsController()
        {
            propertyService = new PropertyService();
            userService = new UserService();
            subscriptionService = new SubscriptionService();
        }

        public ActionResult SignOut()
        {
            Session["userId"] = null;
            Session["username"] = null;
            Session["isUserPropOwner"] = null;
            Session["isUserConsumer"] = null;
            Session["isUserTennant"] = null;

            FormsAuthentication.SignOut();

            return RedirectToAction("home", "home");
        }

        public ActionResult SignIn()
        {
            string username = HttpContext.User.Identity.Name;

            if (!string.IsNullOrEmpty(username))
            {
                startUserSessions();

                if (Roles.IsUserInRole(username, "admin"))
                {
                    return RedirectToAction("verifypayments", "admin");
                }

                return RedirectToAction("Dashboard", "LandlordManagement");
            }

            return View();
        }

        [HttpPost]
        public ActionResult SignIn(string username, string password)
        {
            try
            {
                MembershipUser user = Membership.GetUser(username);

                if (user != null && user.IsLockedOut)
                {
                    string errMessage = "You have exceeded the maximum number of failed attempts <br /> User account has been locked";
                    errMessage += " Reset your password using the link below";

                    Session["invalidUser"] = errMessage;

                    return View();
                }

                if (Membership.ValidateUser(username, password))
                {
                    FormsAuthentication.SetAuthCookie(username, true);

                    startUserSessions(username);

                    if (Roles.IsUserInRole(username, "admin"))
                    {
                        return RedirectToAction("verifypayments", "admin");
                    }

                    return RedirectToAction("Dashboard", "LandlordManagement");
                }
                else
                {
                    Session["invalidUser"] = "Incorrect username or password combination was inserted";
                    return View();
                }
            }
            catch (Exception ex)
            {
                String errMessage = "An unexpected error occurred - please contact system administrator or try again later";
                Session["invalidUser"] = errMessage;
                log.Error(errMessage, ex);

                return View();
            }
        }
        /// <summary>
        /// Set user information to sessions
        /// </summary>
        /// <param name="unitOfWork"></param>
        private void startUserSessions(string username = "")
        {
            using (EasyFindPropertiesEntities dbCtx = new EasyFindPropertiesEntities())
            {
                UnitOfWork unitOfWork = new UnitOfWork(dbCtx);
                Guid userId;

                if (String.IsNullOrEmpty(username))
                {
                    userId = unitOfWork.User.GetUserByEmail(HttpContext.User.Identity.Name).ID;
                    Session["username"] = HttpContext.User.Identity.Name;
                }
                else
                {
                    userId = unitOfWork.User.GetUserByEmail(username).ID;
                    Session["username"] = username;
                }

                var userTypes = unitOfWork.UserTypeAssoc.GetUserTypesByUserID(userId);

                Session["userId"] = userId;
                Session["isUserPropOwner"] = userService.IsUserOfType(userTypes, EFPConstants.UserType.PropertyOwner);
                Session["isUserConsumer"] = userService.IsUserOfType(userTypes, EFPConstants.UserType.Consumer);
                Session["isUserTennant"] = userService.IsUserOfType(userTypes, EFPConstants.UserType.Tennant);
            }
        }

        public ActionResult SignUp()
        {
            return View();
        }

        /// <summary>
        /// Signs up regular user in order for them to make property requisition and comments
        /// </summary>
        /// <param name="user"></param>
        /// <param name="password"></param>
        /// <param name="confirmPassword"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult SignUp(User user, String areaCode, String password, String confirmPassword)
        {
            ErrorModel errorModel = new ErrorModel();
            var isUserCreated = false;

            if (ModelState.IsValid)
            {
                using (EasyFindPropertiesEntities dbCtx = new EasyFindPropertiesEntities())
                {
                    var unitOfWork = new UnitOfWork(dbCtx);

                    try
                    {
                        if (!password.Equals(confirmPassword))
                            throw new Exception("The fields Password and Confirm Password are not equal");

                        var doesUserExist = unitOfWork.User.DoesUserExist(user.Email);

                        if (!doesUserExist)
                        {
                            user = userService.CreateUser(unitOfWork, EFPConstants.UserType.Consumer, "", user.Email, user.FirstName,
                                   user.LastName, user.CellNum, areaCode, DateTime.MinValue);

                            userService.CreateUserAccount(user.Email, password);

                            isUserCreated = true;
                        }
                        else
                            throw new Exception("This email address already exists");

                        unitOfWork.save();

                        if (!propertyService.SendUserCreatedEmail(user, false))
                            throw new Exception("Unable to send user created email");
                    }
                    catch (Exception ex)
                    {
                        if (!String.IsNullOrEmpty(user.Email) && isUserCreated)
                            userService.RemoveUserAccount(unitOfWork,user.Email);

                        errorModel.AddErrorMessage(ex.Message);
                    }
                }
            }
            else
            {
                var errors = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage);
                errorModel.AddErrorMessages(errors);
            }

            return Json(errorModel);
        }

        //loads advertise property view
        public ActionResult AdvertiseProperty()
        {
            AdvertisePropertyViewModel model = new AdvertisePropertyViewModel();

            if (!String.IsNullOrEmpty(HttpContext.User.Identity.Name) && TempData["calledByManagement"] == null)
            {
                Session["userSignedInCheck"] = "Click add property to add a new property";

                return RedirectToAction("Dashboard", "LandlordManagement");
            }

            if (TempData["layout"] != null && TempData["calledByManagement"] != null)
            {
                ViewBag.layout = (String)TempData["layout"];
                ViewBag.calledByManagement = (bool)TempData["calledByManagement"];
            }
            else
                ViewBag.layout = "~/Views/Shared/_Layout.cshtml";

            using (EasyFindPropertiesEntities dbCtx = new EasyFindPropertiesEntities())
            {
                var unitOfWork = new UnitOfWork(dbCtx);

                model.SubscriptionTypes = subscriptionService.GetSubscriptionTypes(unitOfWork);
            }

            return View(model);
        }

        [HttpPost]
        public JsonResult AdvertiseProperty(AdvertisePropertyViewModel model)
        {
            ErrorModel errorModel = new ErrorModel();
            Guid userId = Guid.Empty;

            if (ModelState.IsValid)
            {
                using (EasyFindPropertiesEntities dbCtx = new EasyFindPropertiesEntities())
                {
                    UnitOfWork unitOfWork = new UnitOfWork(dbCtx);

                    if (Session["userId"] != null)
                    {
                        userId = (Guid)Session["userId"];
                    }

                    propertyService.AdvertiseProperty(model, userId, errorModel, unitOfWork);
                }
            }
            else
            {
                var errors = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage);
                errorModel.AddErrorMessages(errors);
            }

            return Json(errorModel);
        }

        //loads the premium feature view
        public ActionResult PremiumFeature()
        {
            return View();
        }

        public ActionResult Requisition()
        {
            return View();
        }

        /// <summary>
        /// Enrolls tennant into a property
        /// </summary>

Views/Accounts/PremiumFeature.cshtml
@{
    ViewBag.Title = "PremiumFeature";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section pageScript
{
    (function(){
    $('#home').attr('class','active');
    })();
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Premium Feature</h2>            
            There will be premium feature available for users that are advertising room accommodations.
            This feature is for landlords who are renting their property and wants to easily manage their property

            The features will include the following:
            <hr />
            <ul>
                <li>Management of Tennants</li>
                <li>Notification of Bills</li>
                <li>Management of Complaints</li>
                <li>Messaging Tennants</li>
            </ul>
            <h3>Pricing</h3>
            The cost of this feature is $3500.00 JMD anually which can be paid through PayPal, Western Union, Money Gram
            and also through the Digicel or Lime credit equivalent.

        </div>
    </div>
</div>

Views/Accounts/RecoverPassword.cshtml
@{
    ViewBag.Title = "JProps - Recover Password";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section pageScript
{
    (function(){
    $.getScript('/Scripts/MainScript.js', function()
    {
    $('#home').attr('class','active');
    displayFadedAnnouncment();
    });
    })();
}
<style>
    .jumbotron-container {
        display: none;
    }
</style>

<a href="#" onclick="goBack();" class="badge badge-primary"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back</a>
<br /><br />
<div class="ctnr-headers">Recover Password</div>
@using (Html.BeginForm("RecoverPassword", "Accounts", FormMethod.Post))
{
    if (TempData["errorMessage"] != null)
    {
        foreach (var msg in (List<String>)TempData["errorMessage"])
        {
            <div class="row">
                <div class="col-md-12">
                    <div class="badge badge-danger">@Html.Raw(msg)</div>
                </div>
            </div>
            <br />
        }
    }
    if (TempData["success"] != null)
    {
        <div class="row">
            <div class="col-md-12">
                <div class="badge badge-info">@((String)TempData["success"])</div>
            </div>
        </div>
        <br />
    }

    <div class="row">
        <div class="col-md-7">
            <label for="email">Email</label>
            <input id="email" value="" type="email" class="form-control" name="email" placeholder="Enter your email address" required />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-7">
            <button class="btn btn-primary btn-sm pull-right" type="submit">Recover my password</button>
        </div>
    </div>
}

Views/Accounts/Registration.cshtml
@{
    ViewBag.Title = "Jamprops - Registration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section pageScript
{
    (function(){
    $('#home').attr('class','active');
    })();

    (function(){
    $.ajax({
    url: 'getRoomPartialView',
    type: 'Get',
    beforeSend: function () {
    $('#ajax-holder').fadeIn();
    },
    success: function (data) {
    $('#ajax-holder').fadeOut();
    $('#property-type').html(data);
    },
    complete:function(){
    $('form').removeData('validator');
    $.validator.unobtrusive.parse($('form'));
    }
    });

    })();

}
@{
    if (Session["registrationErrorMessage"] != null)
    {
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div id="registration-success" class="alert-danger" style="display:none;">
                        <strong>@Session["registrationErrorMessage"].ToString()</strong> <span class="glyphicon glyphicon-exclamation-sign"></span>
                    </div>
                </div>
            </div>
            <div class="row">&nbsp;</div>
        </div>
        Session["registrationErrorMessage"] = null;
    }
}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="ctnr-headers"><label>Ready to advertise ?</label></div>
            <div class="ctnr">
                <div class="ctnr-info">
                    <div class="ctnr-headers"><label>How To Advertise</label></div>
                    <ul>
                        <li><em>To advertise your property using the registration process:</em> simply fill out the form below your property will be added instantly</li>
                        <li>
                            <em>To advertise your property using email:</em>
                            this requires that you send information about your property to this email address:jamprops@hotmail.com;
                            with the following information:
                            <ul>
                                <li>Image of your property (Not required)</li>
                                <li>Your name(required)</li>
                                <li>The address of your property(required)</li>
                                <li>Your contact number(s)(required)</li>
                                <li>Your email address(not required)</li>
                                <li>Any details you think the public needs to know about your property Eg. Cost, security deposit,any facilities included etc.</li>
                            </ul>
                        </li>
                    </ul>
                    <div class="ctnr-headers"><label>Pricing</label></div>
                    The cost to advertise your property is $0.00! that is correct, it's free to advertise your property.
                    <div class="ctnr-headers"><label>Advertisment Period</label></div>
                    Your property will be advertised for a period of two(2) month after which your property will be deleted
                    if the property is still available. You will be required to signin and add your property once again if you want to upload
                    this same property or if you want to advertise another property.
                </div>
            </div>
            <br />
            <div class="panel panel-default">
                <div class="panel-heading"><div class="ctnr-headers">Fill out this form</div></div>
                <div class="panel-body">
                    <div id="landlord-info">@Html.Partial("_OwnerInformationRegistration")</div>
                    <div id="property-type"><div id="ajax-holder" style="display:none;margin-left:45%;"><img src="~/Content/ajax-loader-dark.gif" /></div></div>
                </div>
                <div class="panel-footer"><input id="btnRegister" class="btn btn-primary" type="submit" value="Register" /></div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="ctnr-headers"><label>Coming soon ..........</label></div>
            <div class="ctnr">
                <div class="ctnr-info">
                    There will be premium feature available for users that are advertising room accommodations
                    The features will include the following:
                    <hr />
                    <ul>
                        <li>Management of Tennants</li>
                        <li>Notification of Bills</li>
                        <li>Management of Complaints</li>
                        <li>Messaging Tennants</li>
                    </ul>
                    <a href="~/accounts/premiumfeature" target="_blank">Learn More</a>
                </div>
            </div>
        </div>

    </div>
</div>

Views/Accounts/Requisition.cshtml
@model SS.ViewModels.EnrolmentViewModel
@{
    ViewBag.Title = "Requisition";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

@section pageScript{
    (function(){
    $.getScript('/Scripts/MainScript.js', function()
    {
    setActiveNavigation('home');

    //initializing html content
    $('#ad-placement').hide();
    $('#ad-promotion').hide();

    //initialization of bootstrap popover
    $('[data-toggle="popover"]').popover({
    trigger : 'hover click',
    container: 'body'
    });

    });

    $(function () {
    $(".date-picker").datepicker();
    });

    })();
}

@Html.Partial("_ModalTennantCreated")
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            @using (Html.BeginForm("Enroll", "Accounts", FormMethod.Post, new { @id = "EnrollTennantForm" }))
            {
                <h1>Tennant Personal Information</h1>
                <table class="properties-table-style" width="100%">
                    <tr id="university_info">
                        <td>University Name</td>
                        <td>@Html.TextBoxFor(model => model.InstitutionName, null, new { @class = "form-control" })</td>
                        <td>Programme Name</td>
                        <td>@Html.TextBoxFor(model => model.ProgrammeName, null, new { @class = "form-control" })</td>
                        <td>Programme Start Date</td>
                        <td>@Html.TextBoxFor(model => model.ProgrammeStartDate, null, new { @class = "form-control date-picker" })</td>
                    </tr>
                    <tr>
                        <td>Settlement Period</td>
                        <td>@Html.TextBoxFor(model => model.SettlementPeriod, null, new { @type = "number", @placeholder = "Years", @class = "form-control" })</td>
                        <td class="end_date">Programme End Date</td>
                        <td class="end_date">@Html.TextBoxFor(model => model.ProgrammeEndDate, null, new { @class = "form-control date-picker" })</td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Date of Birth</td>
                        <td>
                            @Html.TextBoxFor(model => model.DOB, null, new { @class = "form-control date-picker" })
                        </td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Password</td>
                        <td>@Html.Password("password", null, new { @class = "form-control" })</td>
                        <td>Confirmed Password</td>
                        <td>@Html.Password("confirmPassword", null, new { @class = "form-control" })</td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Enrolment Key</td>
                        <td>
                            <div class="enrollBtn">
                                @Html.TextBox("enrolmentKey", null, new { @class = "form-control" })
                            </div>
                        </td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input id="submitEnrolment" class="btn " type="submit" value="Enroll"></td>
                    </tr>
                </table>
                @Html.Hidden("propertyId", Request.QueryString["propId"])
                @Html.Hidden("reqID", Request.QueryString["requestId"])
            }
        </div>
    </div>
</div>

Views/Accounts/ResetPassword.cshtml
@{
    ViewBag.Title = "JProps - Reset Password";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .jumbotron-container {
        display: none;
    }
</style>
<div class="ctnr-headers">Reset Password</div>
@if (TempData["errorMessage"] != null)
{
    foreach (var msg in (List<String>)TempData["errorMessage"])
    {
        <div class="row">
            <div class="col-md-12">
                <div class="badge badge-danger">@Html.Raw(msg)</div>
            </div>
        </div>
        <br />
    }
}
@if (Session["accessCodeValid"] == null && TempData["pwdChangedSuccess"] == null)
{
    using (Html.BeginForm("validateAccessCode", "Accounts", FormMethod.Post))
    {
        <input type="hidden" id="userId" name="userId" value="@ViewBag.userId" />
        <div class="row">
            <div class="col-md-7">
                <label for="accessCode">Access Code</label>
                <input id="accessCode" type="text" class="form-control" name="accessCode" placeholder="Access code that was sent to your email" required />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-7">
                <button class="btn btn-primary btn-sm pull-right" type="submit">Submit</button>
            </div>
        </div>
    }
}
else
{
    if (TempData["pwdChangedSuccess"] == null)
    {
        using (Html.BeginForm("resetPassword", "Accounts", FormMethod.Post, new { id = "resetPasswordForm" }))
        {
            <input type="hidden" id="userId" name="userId" value="@ViewBag.userId" />
            <div class="row">
                <div class="col-md-7">
                    <label for="password">Password</label>
                    <input id="password" type="password" class="form-control" name="password" required />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-7">
                    <label for="confirmPassword">Confirm Password</label>
                    <input id="confirmPassword" type="password" class="form-control" name="confirmPassword" required />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-7">
                    <button id="resetPassword" class="btn btn-primary btn-sm pull-right" type="submit">Reset Password</button>
                </div>
            </div>
        }
    }
    else
    {
        <br/>
        <div class="row">
            <div class="col-md-12">
                <span class="badge badge-success">@( ((String)TempData["pwdChangedSuccess"]) )</span> &nbsp;
                <a href="~/accounts/signin">Sign in to your account</a>
            </div>
        </div>
    }
}
                        

Views/Accounts/SignIn.cshtml

@{
    ViewBag.Title = "JProps - SignIn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section pageScript
{
    (function(){
    $.getScript('/Scripts/MainScript.js', function()
    {
    $('#home').attr('class','active');
    displayFadedAnnouncment();
    });
    })();
}
<style>
    .jumbotron-container {
        display: none;
    }
</style>
@{
    if (Session["invalidUser"] != null)
    {
        <div class="row">
            <div class="col-md-12">
                <div id="fadedAnnouncment" class="error" style="display:none; color:#FFFFFF;">
                    <strong>Login Failed</strong> <span class="glyphicon glyphicon-exclamation-sign"></span>
                    <br />@Html.Raw(Session["invalidUser"])
                </div>
            </div>
        </div>
        Session["invalidUser"] = null;
        <br/>
    }
}

    @using (Html.BeginForm("SignIn", "Accounts", FormMethod.Post))
            {

        <div class="ctnr-headers"><label>Sign in</label></div>
        <div class="registration-form">
            <div class="row">
                <div class="col-md-7">
                    <label for="username">Username</label>
                    @Html.TextBox("username", "", new { @required = "true", @class = "form-control" })
                </div>
            </div>
            <br/>
            <div class="row">
                <div class="col-md-7">
                    <label for="password">Password</label>
                    @Html.Password("password", "", new { @required = "true", @class = "form-control" })
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-7">
                    <input type="submit" class="btn btn-primary btn-sm pull-right" value="Sign in">
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-6">
                    <div class="badge badge-light"><label>Not a registered user ? </label> @Html.ActionLink("Sign Up Here", "signup", "accounts")</div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-6">
                    <div class="badge badge-light"><label>Forgot your passsword ? </label> @Html.ActionLink("Reset Your Password", "recoverPassword", "accounts")</div>
                </div>
            </div>
        </div>
    }