Models/Property.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Bill = new HashSet<Bill>();
            this.Complaint = new HashSet<Complaint>();
            this.PropertyImage = new HashSet<PropertyImage>();
            this.PropertyRating = new HashSet<PropertyRating>();
            this.PropertyRequisition = new HashSet<PropertyRequisition>();
            this.Tags = new HashSet<Tags>();
            this.Tennant = new HashSet<Tennant>();
            this.SavedProperties = new HashSet<SavedProperties>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid OwnerID { get; set; }
        public string Title { get; set; }
        public string PurposeCode { get; set; }
        public System.Guid TypeID { get; set; }
        public string AdTypeCode { get; set; }
        public string AdPriorityCode { get; set; }
        public string ConditionCode { get; set; }
        public string CategoryCode { get; set; }
        public string StreetAddress { get; set; }
        public string Division { get; set; }
        public string Community { get; set; }
        public string NearByEstablishment { get; set; }
        public string Country { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string NearByEstablishmentLng { get; set; }
        public string NearByEstablishmentLat { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> SecurityDeposit { get; set; }
        public Nullable<int> Occupancy { get; set; }
        public string GenderPreferenceCode { get; set; }
        public string Description { get; set; }
        public bool Availability { get; set; }
        public string EnrolmentKey { get; set; }
        public string TermsAgreement { get; set; }
        public Nullable<int> TotAvailableBathroom { get; set; }
        public Nullable<int> TotRooms { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<bool> IsReviewable { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateTModified { get; set; }
        public System.DateTime DateTCreated { get; set; }
        public string StreetNumber { get; set; }
        public string AvailabilityModifiedBy { get; set; }
    
        public virtual AdPriority AdPriority { get; set; }
        public virtual AdType AdType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaint { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual PropertyCategory PropertyCategory { get; set; }
        public virtual PropertyCondition PropertyCondition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyImage> PropertyImage { get; set; }
        public virtual PropertyPurpose PropertyPurpose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyRating> PropertyRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyRequisition> PropertyRequisition { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tags> Tags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tennant> Tennant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedProperties> SavedProperties { get; set; }
    }
}

Models/PropertyType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyType()
        {
            this.Property = new HashSet<Property>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string CategoryCode { get; set; }
        public System.DateTime DateTCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Property { get; set; }
        public virtual PropertyCategory PropertyCategory { get; set; }
    }
}

Controllers/PropertiesController.cs
using BotDetect.Web.Mvc;
using log4net;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SS.Code;
using SS.Core;
using SS.Models;
using SS.Services;
using SS.SignalR;
using SS.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Net.Mail;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SS.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private readonly PropertyService propertyService;

        public PropertiesController()
        {
            propertyService = new PropertyService();
        }

        public async Task<ActionResult> getProperties(PropertySearchViewModel model)
        {
            List<FeaturedPropertiesSlideViewModel> featuredPropertiesSlideViewModelList = null;

            using (EasyFindPropertiesEntities dbCtx = new EasyFindPropertiesEntities())
            {
                UnitOfWork unitOfWork = new UnitOfWork(dbCtx);

                var userId = Guid.Empty;

                if (Session["userId"] != null)
                {
                    userId = (Guid)Session["userId"];
                }

                model.PgNo = model.PgNo > 0 ? model.PgNo - 1 : 0;

                if (String.IsNullOrEmpty(model.SearchTerm) && PropertyHelper.CreateFilterList(model, unitOfWork).Count() < 1 && model.Tags == null)
                    return RedirectToAction("/", "home");

                featuredPropertiesSlideViewModelList = await propertyService.PopulatePropertiesViewModel(model, userId, unitOfWork);
            }
            initPropertiesTags(model);
            initPropertiesPgValues(model);

            Session["PropertySearchViewModel"] = model;

            return View(featuredPropertiesSlideViewModelList);
        }

        /// <summary>
        /// set the tag viewbag field with tags associated with the 
        /// returned propertes
        /// </summary>
        /// <param name="model"></param>
        private void initPropertiesTags(PropertySearchViewModel model)
        {
            if (model.Tags == null || (model.Tags != null && model.Tags.Count() == 0))
                ViewBag.tags = setPropertyTags();
            else
                ViewBag.tags = setPropertyTags(model.Tags);
        }

        /// <summary>
        /// initialize the viewbag fields on the getProperties page
        /// </summary>
        /// <param name="model"></param>
        private void initPropertiesPgValues(PropertySearchViewModel model)
        {
            ViewBag.activeNavigation = model.IsStudentAccommodationCat ? "isStudentAccommodationCat" : PropertyHelper.mapPropertyCategoryCodeToName(model.PropertyCategory);
            ViewBag.isStudentAccommodationCat = model.IsStudentAccommodationCat;
            ViewBag.category = PropertyHelper.mapPropertyCategoryCodeToName(model.PropertyCategory);
            ViewBag.runningHeader = getRunningHeader(model);
            ViewBag.searchViewModel = model;
            ViewBag.fetchAmount = model.take;
            ViewBag.pageNumber = model.PgNo + 1;
        }
        /// <summary>
        /// Creates the running header for each properties searched result page
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        private String getRunningHeader(PropertySearchViewModel model)
        {
            String header = "Results ";

            if (!String.IsNullOrEmpty(model.SearchTerm))
            {
                if (model.DistanceRadius > 0)
                    header += "for properties that are " + model.DistanceRadius + " KM from " + model.SearchTerm;
                else
                    header += "for the search : " + model.SearchTerm;
            }
            else if (!String.IsNullOrEmpty(model.PropertyCategory))
            {
                if (model.IsStudentAccommodationCat)
                {
                    header += "for properties in the Student Accommodation category";
                }
                else
                {
                    if (EFPConstants.PropertyCategory.RealEstate.Equals(model.PropertyCategory))
                    {
                        header += "for properties in the Real Estate category";
                    }
                    else
                        header += "for properties in the " + PropertyHelper.mapPropertyCategoryCodeToName(model.PropertyCategory) + " category";
                }
            }

            return header;
        }

        public async Task<ActionResult> getNearbyProperties(String distanceMtxInfo, int? pgNo, double? distanceRadius)
        {
            List<FeaturedPropertiesSlideViewModel> featuredPropertiesSlideViewModelList = null;
            var userId = Guid.Empty;

            using (EasyFindPropertiesEntities dbCtx = new EasyFindPropertiesEntities())
            {
                UnitOfWork unitOfWork = new UnitOfWork(dbCtx);

                var searchViewModel = (PropertySearchViewModel)Session["PropertySearchViewModel"];

                if (pgNo.HasValue)
                    searchViewModel.PgNo = pgNo.Value;

                if (!distanceRadius.HasValue)
                    searchViewModel.DistanceRadius = 20;
                else
                    searchViewModel.DistanceRadius = distanceRadius.Value;

                if (Session["userId"] != null)
                {
                    userId = (Guid)Session["userId"];
                }

                if (!String.IsNullOrEmpty(distanceMtxInfo) && !distanceMtxInfo.Equals("null"))
                    Session["distanceMtxInfo"] = distanceMtxInfo;
                else if (Session["distanceMtxInfo"] != null)
                    distanceMtxInfo = (String)Session["distanceMtxInfo"];
                else
                    return RedirectToAction("/", "home");

                if (searchViewModel == null)
                    return RedirectToAction("/", "home");

                if (!String.IsNullOrEmpty(distanceMtxInfo))
                {
                    //distance radius is in KM TODO give option to convert to miles
                    //will be used to eliminate properties that are of further distance
                    var model = JsonConvert.DeserializeObject<NearbyPropertySearchViewModel>(distanceMtxInfo);
                    var revisedModel = propertyService.NarrowSearchResultsToDistanceRadius(model, searchViewModel.DistanceRadius);

                    searchViewModel.PgNo = searchViewModel.PgNo > 0 ? searchViewModel.PgNo - 1 : 0;
                    featuredPropertiesSlideViewModelList = await propertyService.PopulatePropertiesViewModel(revisedModel, searchViewModel, userId, unitOfWork);

                    ViewBag.SearchTerm = searchViewModel.SearchTerm;
                    ViewBag.SearchType = searchViewModel.SearchType;
                    ViewBag.DistanceRadius = searchViewModel.DistanceRadius;
                    ViewBag.NearByPropModel = revisedModel;

                    initPropertiesTags(searchViewModel);
                    initPropertiesPgValues(searchViewModel);
                }
            }

            return View("getProperties", featuredPropertiesSlideViewModelList);
        }

        [HttpGet]
        public async Task<JsonResult> GetPropertiesCoordinates(PropertySearchViewModel model)
        {
            Array propertyCoordinates = null;

            using (EasyFindPropertiesEntities dbCtx = new EasyFindPropertiesEntities())
            {
                UnitOfWork unitOfWork = new UnitOfWork(dbCtx);

                propertyCoordinates = await propertyService.PopulateModelForPropertyCoordinates(model, unitOfWork);

                Session["PropertySearchViewModel"] = model;
            }

            return Json(propertyCoordinates, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> GetPropertiesCounts(PropertySearchViewModel model)
        {
            int count = 0;

            using (EasyFindPropertiesEntities dbCtx = new EasyFindPropertiesEntities())
            {
                UnitOfWork unitOfWork = new UnitOfWork(dbCtx);
                
                count = await propertyService.GetPropertiesCount(model, unitOfWork);
            }

            return Json(count, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> GetNearbyPropertiesCounts(List<NearbyPropertySearchModel> model, PropertySearchViewModel searchViewModel)
        {
            int count = 0;

            using (EasyFindPropertiesEntities dbCtx = new EasyFindPropertiesEntities())
            {
                UnitOfWork unitOfWork = new UnitOfWork(dbCtx);

                if (model != null)
                {
                    count = await propertyService.GetNearbyPropertiesCount(model, searchViewModel, unitOfWork);
                }
            }

            return Json(count, JsonRequestBehavior.AllowGet); ;
        }

        public ActionResult getProperty(Guid id)
        {
            SelectedPropertyViewModel property = null;

            using (EasyFindPropertiesEntities dbCtx = new EasyFindPropertiesEntities())
            {
                UnitOfWork unitOfWork = new UnitOfWork(dbCtx);

                var searchViewModel = (PropertySearchViewModel)Session["PropertySearchViewModel"];

                ViewBag.searchViewModel = searchViewModel;

                property = propertyService.GetProperty(id, unitOfWork);
            }

            return View(property);
        }


Controllers/RoomsController.cs
using SS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SS.Controllers
{
    public class RoomsController : Controller
    {
        [HttpPost]
        public ActionResult RequestRoom(REQUISITIONS requisitions, Guid accommodationID)
        {
            JAHomesEntities dbCtx = new JAHomesEntities();

            dbCtx.sp_make_requisition(accommodationID, requisitions.FIRST_NAME, requisitions.LAST_NAME,requisitions.GENDER, requisitions.EMAIL, requisitions.CELL);

            return RedirectToAction("Home", "Home");
        }

        [HttpPost]
        public ActionResult RetrieveSelected(string value)
        {
            JAHomesEntities dbCtx = new JAHomesEntities();

            return Content(dbCtx.ACCOMMODATIONS.Where(r => r.ID.ToString() == value).Select(r => r.ROOM_PIC_URL).Single());
        }
    }
}

Views/Properties/getProperty.cshtml
@model SS.ViewModels.SelectedPropertyViewModel
@using SS.Core
@using SS.Models
@{
    ViewBag.Title = "JProps - " + "Properties being " + Model.AdType + " in " + Model.Community + ", " + Model.Division + ", " + Model.Country;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section pageCss
{
    <link href="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
    <link href="@BotDetect.Web.CaptchaUrls.Absolute.LayoutStyleSheetUrl" rel="stylesheet" type="text/css" />
}

@section pageScriptSrc
{
    <script src="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>
}

@section pageScript
{
    (function(){
    $.getScript('/Scripts/MainScript.js', function()
    {
    setActiveNavigation('home');
    $.getScript('/Scripts/PropertiesScript.js',function(){
    });
    });
    })();
}

@if (!Model.isAvailable)
{
    <div class="ctnr-headers">This property is no longer available</div>
}
else
{
    @Html.Partial("_ModalPropertyRequisitionSuccess")
    <a href="#" onclick="goBack();" class="badge badge-primary"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back</a>
    <br /><br />
    <div class="row">
        <div class="col-md-12">
            <div class="ctnr-headers">
                @{
                    String adTypeName = "";
                    if (Model.AdType.Equals("Rent"))
                    {
                        adTypeName = "Rented";
                    }
                    else if (Model.AdType.Equals("Sale")) { adTypeName = "Sold"; } else { adTypeName = "Leased"; }
                }
                <label>
                    <strong>Properties being @adTypeName in @Model.Community, @Model.Division, @Model.Country</strong>
                    <a href="#" title=""><i class="fa fa-map-marker" aria-hidden="true"></i></a>
                </label>
                <div class="date-added float-md-right">Added @Model.DateAddedModified</div>
            </div>
        </div>
    </div>
        <br />
        <div class="row">
            <div class="col-md-12 bg-lighter">
                <div class="fotorama" data-nav="thumbs" data-allowfullscreen="true" data-width="100%" data-height="40%">
                    @{
                        foreach (var propImageUrl in Model.PropertyImageURLs)
                        {
                            <a href="~/Uploads/@propImageUrl">
                                <img src="~/Uploads/@propImageUrl" />
                            </a>
                        }

                    }
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Property Details</div>
                    <div class="card-body">
                        <div>
                            <div class="details-col-header">Price <span class="details-col-det"> @String.Format("{0:C}", Model.Price)</span></div>
                            <div class="details-col-header">Security Deposit <span class="details-col-det"> @String.Format("{0:C}", Model.SecurityDeposit) </span></div>
                            <br />
                            <p>@Model.Description</p>
                        </div>
                        <div class="card" style="width:70%;">
                            <div class="card-header bg-transparent">Owner Contact</div>
                            <div class="card-body">
                                <div><i class="fa fa-user-o fa-2x" aria-hidden="true"></i> <span>@Model.OwnerFirstName @Model.OwnerLastName </span></div>
                                <div><i class="fa fa-mobile fa-2x" aria-hidden="true"></i> <span>@Model.OwnerCellNumber</span></div>
                                <br />
                                <div><button id="requestPropertyProxyBtn" class="btn btn-outline-primary btn-sm">Request Property</button></div>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="card">
                    <div class="card-header">Property's Key Features</div>
                    <div class="card-body">
                        @{
                            if (Model.PropertyCategoryCode.Equals(EFPConstants.PropertyCategory.RealEstate))
                            {
                                <div class="details-col-header">Total Bedroom Amount <span class="details-col-det">@Model.TotalBedrooms</span></div>
                                <div class="details-col-header">Total Bathroom Amount <span class="details-col-det">@Model.TotalBathrooms</span></div>
                                <div class="details-col-header">Occupancy <span class="details-col-det">@Model.Occupancy</span></div>
                                <div class="details-col-header">Property Area <span class="details-col-det">@Model.Area</span></div>
                            }
                            else if (Model.PropertyCategoryCode.Equals(EFPConstants.PropertyCategory.Lot))
                            {
                                <div class="details-col-header">Property Area <span class="details-col-det">@Model.Area</span></div>
                            }
                            else
                            {
                                <div class="details-col-header">Condition <span class="details-col-det">@Model.PropertyCondition</span></div>
                            }
                            foreach (var tag in Model.Tags)
                            {
                                <div class="details-col-header">@tag <span class="details-col-det">Yes</span></div>
                            }
                        }
                    </div>
                </div>

                <!--@*
                <ul class="property-ratings">
                    <a href="#" title="property ratings">
                        @if (Model.PropertyAverageRatings > 0)
                        {
                            for (int ratingCount = 1; ratingCount <= Model.PropertyAverageRatings; ratingCount++)
                            {
                                <li><span class="glyphicon glyphicon-star"></span></li>
                            }
                        }
                        else
                        {
                            int maxRating = 5;
                            for (int ratingCount = 1; ratingCount <= maxRating; ratingCount++)
                            {
                                <li><span class="empty glyphicon glyphicon-star-empty"></span></li>
                            }
                        }
                    </a>
                    <!---
                    <li><a href=""><img src="~/Content/facebook.svg" /></a></li>
                    <li><a href=""><img src="~/Content/twitter.svg" /></a></li>
                    <li><a href=""><img src="~/Content/google-plus.svg" /></a></li>
                </ul>*@-->
            </div>
        </div>
        <hr />@* TODO - implement property reviews
            <div class="row">
                <div id="property-reviews" class="col-md-12">
                    <div class="ctnr-info"><strong>Property Reviews</strong></div>
                    @{
                        if (Model.PropRatings != null && Model.PropRatings.Count() > 0)
                        {
                            foreach (var review in Model.PropRatings)
                            {
                                <div class="row">&nbsp;</div>
                                for (int i = 1; i < 5; i++)
                                {
                                    <div class="row">&nbsp;</div>
                                    <ul class="property-ratings">
                                        <a href="#" title="@review.Ratings out of 5 stars">
                                            @for (int ratingCount = 1; ratingCount <= review.Ratings; ratingCount++)
                                            {
                                                <li><span class="glyphicon glyphicon-star"></span></li>
                                            }
                                        </a>
                                        <li><span class="ctnr-info" style="font-size13px;"><em>By @review.CritqueBy</em></span></li>
                                        <li><span class="ctnr-info" style="font-size13px;"><em>On @review.DateTCreated.ToShortDateString()</em></span></li>
                                    </ul>
                                    <br />
                                    <div class="contact-info-container" style="width100%">
                                        <div class="contact-info-content">@review.Comments property has a warming atmosphere property has a warming atmosphere property has a warming atmosphere property has a warming atmosphere property has a warming atmosphere property has a warming atmosphere property has a warming atmosphere property has a warming atmosphere property has a warming atmosphere property has a warming atmosphere</div>
                                    </div>
                                    <br />
                                }
                                <div class="row">&nbsp;</div>
                            }
                        }
                        else
                        {
                            <br />
                            <div class="contact-info-container" style="width:100%">
                                <center>
                                    <div class="contact-info-header ctnr-info">Property has not yet been reviewed</div>
                                </center>
                            </div>
                        }
                    }
                </div>
            </div>
            <br />*@
                            <div class="row" id="property-requisition-question">
                                <div id="property-requisition" class="col-md-12">
                                    @if (Session["userId"] != null)
                {
                    using (Html.BeginForm("RequestProperty", "Properties", FormMethod.Post, new { id = "requestPropertyForm" }))
                    {
                                            <div style="display:none;" class="col-md-12 error-container"></div>
                                            <div class="ctnr-headers"><strong>Request Property or Ask a Question</strong></div>
                                            <br />
                                            <div class="card">
                                                <div class="card-header">
                                                    <div class="btn-group btn-group-toggle" data-toggle="buttons">
                                                        <label class="contactPurpose btn btn-secondary active">
                                                            @Html.RadioButton("contactPurpose", "requisition", true, new { autocomplete = "off", id = "contact-purpose-req" }) Request Property
                                                        </label>
                                                        <label class="contactPurpose btn btn-secondary">
                                                            @Html.RadioButton("contactPurpose", "message", new { autocomplete = "off", id = "contact-purpose-msg" }) Ask Question
                                                        </label>
                                                    </div>
                                                </div>
                                                <div class="card-body">
                                                    <div class="contact-msg hide">
                                                        <textarea id="msg" cols="5" class="form-control" name="msg" placeholder="Optional message to the property owner"></textarea>
                                                        <br />
                                                    </div>
                                                    <div id="mvcCaptcha">@Html.Partial("_PartialMvcCaptcha")</div>
                                                    <br />
                                                    <div class="requestPropertySec float-right">
                                                        <button id="requestPropertyBtn" type="submit" class="btn btn-sm btn-accent">Submit</button>
                                                    </div>
                                                </div>
                                            </div>
                                            @Html.Hidden("PropertyID", Model.ID)
                                        }
                                    }
                                    else
                                    {
                                        <div class="ctnr-info"><strong><a href="~/accounts/signin">Sign In</a> to Request Property or Ask a Question</strong></div>
                                    }
                                </div>
                            </div>
                            }